import CallToAction from '@/components/home/CallToAction'
import FeatureCards from '@/components/home/FeatureCards'
import NavBar from '@/components/ui/NavBar'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Revius</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className="flex-grow">
        <CallToAction />
        <FeatureCards />
      </main>
    </>
  )
}
