import NavBar from '@/components/ui/NavBar'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Revius</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className="flex-grow">
        <section className="p-8 bg-gradient-to-r from-blue-700 to-blue-500 text-white min-h-screen flex justify-center items-center">
          <h2 className="text-8xl font-bold text-center">
            Revius.cl coming soon!
          </h2>
        </section>
      </main>
    </>
  )
}
